package delivery

import (
	"bytes"
	"fmt"
	"github.com/k0marov/gometa/lib/generator/gen"
	"github.com/k0marov/gometa/lib/helpers"
	"github.com/k0marov/gometa/lib/schema"
	"io"
	"text/template"
)

var entityTemplate = template.Must(template.New("").Parse(`
package {{ .PackageName }} 

import (
    "{{.EntityImport}}"
)

type Create{{ .Entity.Name }}Req struct {
	{{ range $field := .Entity.Fields }} 
		{{ if $field.IsPrimaryKey }} {{ continue }} {{ end }}
		{{ $field.GoName }} {{ $field.Type.GolangType }} {{ $field.GetJsonTags }} 
	{{ end }}
}

type {{ .Entity.Name }} struct {
	{{ range $field := .Entity.Fields }} 
	{{ $field.GoName }} {{ $field.Type.GolangType }} {{ $field.GetJsonTags }} {{ end }}
}

func (e *{{ .Entity.Name }}) ToEntity() models.{{.Entity.Name}} {
	return models.{{ .Entity.Name }}{
		{{ range $field := .Entity.Fields }} 
		{{ $field.GoName }}: e.{{ $field.GoName }}, {{ end }}
	}
}

func MapEntity(e models.{{ .Entity.Name }}) {{ .Entity.Name }} {
	return {{ .Entity.Name }}{
		{{ range $field := .Entity.Fields }} 
		{{ $field.GoName }}: e.{{ $field.GoName }}, {{ end }}
	}
}

func (c Create{{.Entity.Name}}Req) ToDTO() models.Create{{.Entity.Name}}DTO {
	return models.Create{{.Entity.Name}}DTO{
		{{ range $field := .Entity.Fields }} 
			{{ if $field.IsPrimaryKey }} {{ continue }} {{ end }}
			{{ $field.GoName }}: c.{{ $field.GoName }},
		{{ end }}
	}
}
`))

// TODO: remove unneeded newline after models.{

func GenerateMappers(out io.Writer, ent schema.Entity, genCtx gen.GenerationContext) error {
	templateData := struct {
		gen.GenerationContext
		Entity schema.Entity
	}{
		GenerationContext: genCtx,
		Entity:            ent,
	}
	var generated bytes.Buffer
	err := entityTemplate.Execute(&generated, templateData)
	if err != nil {
		return fmt.Errorf("error while executing json mappers template: %w", err)
	}
	if err := helpers.WriteFormatted(generated.Bytes(), out); err != nil {
		return fmt.Errorf("while formatting json mappers file: %w", err)
	}
	return nil
}
