package repository

import (
	"bytes"
	"fmt"
	"github.com/k0marov/gometa/lib/generator/gen"
	"github.com/k0marov/gometa/lib/helpers"
	"io"
	"text/template"
)

// TODO: add logs and error wraps in repo template
var repoTemplate = template.Must(template.New("").Parse(`
package {{.PackageName}} 

import (
    "gorm.io/gorm"
	"log"
	"fmt"
	"errors"
    "{{.EntityImport}}"
	"{{.ModuleName}}/internal/clienterrs"
)

type RepositoryImpl struct {
    db *gorm.DB
}

func NewRepositoryImpl(db *gorm.DB) *RepositoryImpl {
    if err := db.AutoMigrate(&models.{{.EntityName}}{}); err != nil {
		log.Fatalf("failed migrating for {{.EntityName}}: %v", err) 
	}
    return &RepositoryImpl{db: db}
}

func (r *RepositoryImpl) Create(entity *models.{{ .EntityName }}) (*models.{{.EntityName}}, error) {
    return entity, r.db.Create(entity).Error
}

func (r *RepositoryImpl) Get(id string) (*models.{{ .EntityName }}, error) {
    entity := new(models.{{ .EntityName }})
    err := r.db.Where("id = ?", id).First(entity).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, clienterrs.ErrNotFound
	}
    return entity, err
}

func (r *RepositoryImpl) GetAll() ([]*models.{{ .EntityName }}, error) {
	var entities []*models.{{ .EntityName }} 
	if err := r.db.Find(&entities).Error; err != nil {
		return nil, fmt.Errorf("getting all rows from sql: %w", err) 	
	}
	return entities, nil
}

func (r *RepositoryImpl) Update(entity *models.{{ .EntityName }}) error {
    return r.db.Model(entity).Updates(entity).Error
}

func (r *RepositoryImpl) Delete(id string) error {
    return r.db.Delete(&models.{{.EntityName}}{}, id).Error
}
`))

// TODO: добавить проброску контекста везде

func Generate(out io.Writer, genCtx gen.GenerationContext) error {
	templateData := struct {
		gen.GenerationContext
	}{
		GenerationContext: genCtx,
	}
	var generated bytes.Buffer
	err := repoTemplate.Execute(&generated, templateData)
	if err != nil {
		return fmt.Errorf("error while executing repository template: %w", err)
	}
	if err := helpers.WriteFormatted(generated.Bytes(), out); err != nil {
		return fmt.Errorf("while formatting repository file: %w", err)
	}
	return nil
}
