package repository

import (
	"bytes"
	"github.com/k0marov/gometa/lib/helpers"
	"github.com/k0marov/gometa/lib/schema"
	"io"
	"log"
	"text/template"
)

// TODO: add logs and error wraps in repo template
// TODO: add creating SQL table in repo
var repoTemplate = template.Must(template.New("").Parse(`
package {{.PackageName}} 

import (
    "gorm.io/gorm"
    . "{{.EntityImport}}"
)

type {{ .EntityName }}RepositoryImpl struct {
    db *gorm.DB
}

func New{{ .EntityName }}RepositoryImpl(db *gorm.DB) {{ .EntityName }}RepositoryImpl {
    db.AutoMigrate(&{{.EntityName}}{})
    return {{ .EntityName }}RepositoryImpl{db: db}
}

func (r {{ .EntityName }}RepositoryImpl) Create(entity *{{ .EntityName }}) (*{{.EntityName}}, error) {
    return entity, r.db.Create(entity).Error
}

func (r {{ .EntityName }}RepositoryImpl) Get(id uint64) (*{{ .EntityName }}, error) {
    entity := new({{ .EntityName }})
    err := r.db.Limit(1).Where("id = ?", id).First(entity).Error
	//if err == gorm.ErrRecordNotFound {
	//	return nil, client_errors.Err{{.EntityName}}NotFound
	//}
    return entity, err
}

func (r {{ .EntityName }}RepositoryImpl) Update(entity *{{ .EntityName }}) error {
    return r.db.Model(entity).Updates(entity).Error
}

func (r {{ .EntityName }}RepositoryImpl) Delete(id uint64) error {
    return r.db.Delete(&{{.EntityName}}{}, id).Error
}
`))

func Generate(ent schema.Entity, out io.Writer, packageName, entityImport string) {
	templateData := struct {
		PackageName  string
		EntityImport string
		EntityName   string
	}{
		PackageName:  packageName,
		EntityImport: entityImport,
		EntityName:   ent.Name,
	}
	var generated bytes.Buffer
	err := repoTemplate.Execute(&generated, templateData)
	if err != nil {
		log.Fatalf("error while executing repository template: %v", err)
	}
	if err := helpers.WriteFormatted(generated.Bytes(), out); err != nil {
		log.Fatalf("while formatting repository file: %v", err)
	}
}
